name: nuntium
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  async: 2.11.0
  auto_route: 9.2.2
  bloc: 8.1.4
  cached_network_image: 3.4.1
  carousel_slider: 5.0.0
  collection: 1.18.0
  connectivity_plus: 6.0.5
  cupertino_icons: 1.0.8
  dartz: 0.10.1
  dio: 5.7.0
  drift: 2.20.2
  easy_localization: 3.0.7
  easy_localization_loader: 2.0.2
  easy_logger: 0.0.2
  firebase_auth: 5.3.1
  firebase_core: 3.6.0
  firebase_messaging: 15.1.3
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  flutter_dotenv: 5.1.0
  flutter_form_builder: 9.4.1
  flutter_slidable: 3.1.1
  flutter_svg: 2.0.10+1
  form_builder_validators: 11.0.0
  freezed_annotation: 2.4.4
  get_it: 7.7.0
  google_sign_in: 6.2.1
  injectable: 2.4.4
  json_annotation: 4.9.0
  logger: 2.4.0
  path: 1.9.0
  path_provider: 2.1.4
  permission_handler: 11.3.1
  pretty_dio_logger: 1.4.0
  retry: 3.1.2
  rxdart: 0.28.0
  shared_preferences: 2.3.2
  sign_in_with_apple: 6.1.2
  sqlite3_flutter_libs: 0.5.24
  uuid: 4.5.0
  vector_graphics: 1.1.11+1
  webview_flutter: 4.9.0 
  

dev_dependencies:
  auto_route_generator: 9.0.0
  build_runner: 2.4.12
  drift_dev: 2.20.3
  flutter_gen_runner: 5.7.0
  flutter_native_splash: 2.4.1
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  injectable_generator: 2.6.2
  json_serializable: 6.8.0
  surf_lint_rules: 3.1.0
  vector_graphics_compiler: 1.1.11+1

flutter:
  uses-material-design: true
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProText-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SFProText-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SFProText-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFProText-HeavyItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/SFProText-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProText-LightItalic.ttf
          weight: 300
          style: italic

  assets:
    - .env
    - assets/translations/
    - assets/images/
    - assets/svg_compiled/

flutter_gen:
  output: lib/generated