// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAMfarWYDrSzJ3RtwpXU-Kbe7BSSjIe0M',
    appId: '1:845812663111:web:fa83876c0999149d1a0262',
    messagingSenderId: '845812663111',
    projectId: 'nuntium-demo-app',
    authDomain: 'nuntium-demo-app.firebaseapp.com',
    storageBucket: 'nuntium-demo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5hMm-YvaK1AkERJaptEG03D72sLVL0ug',
    appId: '1:41978289999:android:6a0a57cde3e21a106e6f3a',
    messagingSenderId: '41978289999',
    projectId: 'nuntium-7922c',
    storageBucket: 'nuntium-7922c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0XMdzb2azYhy-tf4UqdV_pe-aQi5bAOU',
    appId: '1:41978289999:ios:b81fefc3252a8e4f6e6f3a',
    messagingSenderId: '41978289999',
    projectId: 'nuntium-7922c',
    storageBucket: 'nuntium-7922c.appspot.com',
    iosClientId: '41978289999-tk4k7qd61fgp123oh6c93v7on6dpq9ie.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuntium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY5NRELMKZYUSCtU69XRrbqT4JwiRvLxY',
    appId: '1:845812663111:ios:31e5a7cf1d01ee8f1a0262',
    messagingSenderId: '845812663111',
    projectId: 'nuntium-demo-app',
    storageBucket: 'nuntium-demo-app.appspot.com',
    androidClientId: '845812663111-s0k9cf57selhld0p1j7f7bct6u9olm5d.apps.googleusercontent.com',
    iosClientId: '845812663111-umgo29nkkd702n5817plrijpfvqu8rha.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuntiumDemoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAMfarWYDrSzJ3RtwpXU-Kbe7BSSjIe0M',
    appId: '1:845812663111:web:41c3977e1ec3beaf1a0262',
    messagingSenderId: '845812663111',
    projectId: 'nuntium-demo-app',
    authDomain: 'nuntium-demo-app.firebaseapp.com',
    storageBucket: 'nuntium-demo-app.appspot.com',
  );

}